name: example
description: "example for env_indicator"
publish_to: 'none'
version: 0.1.0+30
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  env_indicator:
    path: ../
  flutter_dotenv: ^6.0.1

flutter:
  assets:
    - .env

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
